import HautevilleHouse.CatalanMihailescuTheoremCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.CatalanMihailescuTheoremCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.CatalanMihailescuTheoremCanonicalLaneLean.GateLemmas
import HautevilleHouse.CatalanMihailescuTheoremCanonicalLaneLean.FinalTheorem
import HautevilleHouse.CatalanMihailescuTheoremCanonicalLaneLean.ExponentialDiophantinePackage
import HautevilleHouse.CatalanMihailescuTheoremCanonicalLaneLean.CyclotomicFieldArithmetic
import HautevilleHouse.CatalanMihailescuTheoremCanonicalLaneLean.LinearFormsLogarithms
import HautevilleHouse.CatalanMihailescuTheoremCanonicalLaneLean.ModularMethod

namespace HautevilleHouse
namespace CatalanMihailescuTheoremCanonicalLaneLean

-- Root module for the Catalan-Mihăilescu Theorem Canonical Lane package.

end CatalanMihailescuTheoremCanonicalLaneLean
end HautevilleHouse
